import "tailwindcss/base"
import "tailwindcss/components"
import "tailwindcss/utilities"
import './application.scss'
import './product.scss'
import './home.scss'
import './navbar.scss'
import './cards.scss'
import './login.scss'
import './application.scss'
